In [25]:
import pandas as pd
import numpy as np

In [31]:
df = pd.read_csv("car-sales-extended-missing-data.csv")

In [32]:
df.head()

     Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [33]:
df.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [34]:
#getting data ready

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

In [35]:
#loading random forest regressor

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

In [36]:
#setting up random seed using numpy
np.random.seed(42)

In [71]:
#setting up the dataset by deleting the rows with missing price values

df.dropna(subset = ['Price'], inplace = True)
X = df.drop("Price", axis = 1)
Y = df["Price"]

In [72]:
df.isnull().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [73]:
#defining categorical data

categorical_features = ["Make", "Colour"]
categorical_transform = Pipeline(
    steps = [
        ('imputer', SimpleImputer(strategy = "constant", fill_value = "missing")),
        ('onehot', OneHotEncoder(handle_unknown = "ignore"))          
])

#definig door data because most of them have 4 doors
door_features = ["Doors"]
door_transform = Pipeline(
    steps = [
        ('imputer', SimpleImputer(strategy = "constant",fill_value = 4 )),
        
    ]
)

#Numeric data 
numeric_features = ["Odometer (KM)"]
numeric_transform = Pipeline(
    steps = [
        ("imputer", SimpleImputer(strategy = "mean"))
    ]
)

In [74]:
#preprocessing of data

preprocessor = ColumnTransformer(
    transformers =  [
        ("cat", categorical_transform, categorical_features),
        ("door", door_transform, door_features),
        ("numeric", numeric_transform, numeric_features)
    ]
)

In [75]:
df.head()

     Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [76]:
#Creating a preprocessing and modeling pipeline

ModelPipeline = Pipeline(
    steps = [
        ("pre-processor", preprocessor),
        ("Model", RandomForestRegressor())
    ]
)

In [80]:
#creating the test train split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3)

In [81]:
ModelPipeline.fit(X_train,Y_train)
ModelPipeline.score(X_test, Y_test)

0.2115165526131353